<a href="https://colab.research.google.com/github/dewi-ops/Data-Analytic-and-Infrastucture/blob/main/UAS_DAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install schedule

Collecting schedule
  Downloading schedule-1.2.2-py3-none-any.whl.metadata (3.8 kB)
Downloading schedule-1.2.2-py3-none-any.whl (12 kB)
Installing collected packages: schedule
Successfully installed schedule-1.2.2

In [2]:
import pandas as pd
import sqlite3
import json
import re
import logging
import schedule
import time

from datetime import datetime

In [3]:
from google.colab import files

uploaded = files.upload()

Saving source_uas (2).zip to source_uas (2).zip

In [4]:
!unzip "source_uas (2).zip"

Archive:  source_uas (2).zip
   creating: source_uas/
  inflating: source_uas/siswa_sekolah_a.csv
  inflating: source_uas/siswa_sekolah_b.sql
  inflating: source_uas/siswa_sekolah_c.json

In [5]:
import os

for file in os.listdir():
    print(file)

.config
source_uas
source_uas (2).zip
sample_data

In [6]:
import os

for file in os.listdir("source_uas"):
    print(file)

siswa_sekolah_b.sql
siswa_sekolah_a.csv
siswa_sekolah_c.json

In [7]:
import pandas as pd

df_csv = pd.read_csv("source_uas/siswa_sekolah_a.csv")

print("Jumlah data:", len(df_csv))
display(df_csv.head())

print("\nKolom:")
print(df_csv.columns.tolist())

Jumlah data: 4

,nisn,nama_siswa,jenis_kelamin,tanggal_lahir,sekolah,alamat_sekolah,jenjang,kota
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta

Kolom:
['nisn', 'nama_siswa', 'jenis_kelamin', 'tanggal_lahir', 'sekolah', 'alamat_sekolah', 'jenjang', 'kota']

In [8]:
import json

with open(
    "source_uas/siswa_sekolah_c.json",
    "r",
    encoding="utf-8"
) as f:
    data_json = json.load(f)

df_json = pd.DataFrame(data_json)

print("Jumlah data:", len(df_json))
display(df_json.head())

print("\nKolom:")
print(df_json.columns.tolist())

Jumlah data: 3

                                          data_siswa
0  {'identitas': {'nisn': '0031234573', 'nama': '...
1  {'identitas': {'nisn': '0031234574', 'nama': '...
2  {'identitas': {'nisn': '0031234575', 'nama': '...

Kolom:
['data_siswa']

In [9]:
with open(
    "source_uas/siswa_sekolah_b.sql",
    "r",
    encoding="utf-8"
) as f:

    sql_content = f.read()

print(sql_content)

-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 26, 2025 at 04:19 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sekolah_b`
--

-- --------------------------------------------------------

--
-- Table structure for table `siswa_sekolah_b`
--

CREATE TABLE `siswa_sekolah_b` (
  `id_mysql` int(11) NOT NULL,
  `nomor_induk` varchar(15) DEFAULT NULL,
  `nama_lengkap` varchar(100) DEFAULT NULL,
  `jk` enum('L','P') DEFAULT NULL,
  `tgl_lahir` date DEFAULT NULL,
  `nama_sekolah_asli` varchar(100) DEFAULT NULL,
  `alamat_sekolah_asli` text DEFAULT NULL,
  `tingkat` varchar(10) DEFAULT NULL,
  `kota_sekolah` varchar(50) DEFAULT NULL,
  `tanggal_daftar` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `siswa_sekolah_b`
--

INSERT INTO `siswa_sekolah_b` (`id_mysql`, `nomor_induk`, `nama_lengkap`, `jk`, `tgl_lahir`, `nama_sekolah_asli`, `alamat_sekolah_asli`, `tingkat`, `kota_sekolah`, `tanggal_daftar`) VALUES
(1, 'SMP-001', 'Rina Wijaya', 'P', '2009-07-15', 'SMP PGRI 1 Semarang', 'Jl. Dahlia No.25', 'SMP', 'Semarang', '2025-10-26 13:28:14'),
(2, 'SMP-002', 'Fajar Nugroho', 'L', '2009-11-30', 'SMP PGRI 1 Semarang', 'Jl. Dahlia No.25', 'SMP', 'Semarang', '2025-10-26 13:28:14'),
(3, 'SMA-001', 'Lisa Permata', 'P', '2007-04-22', 'SMA Kristen 1 Surakarta', 'Jl. Sakura No.8', 'SMA', 'Surakarta', '2025-10-26 13:28:14'),
(4, 'SMA-002', 'Hendra Kurniawan', 'L', '2007-12-10', 'SMA Kristen 1 Surakarta', 'Jl. Sakura No.8', 'SMA', 'Surakarta', '2025-10-26 13:28:14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `siswa_sekolah_b`
--
ALTER TABLE `siswa_sekolah_b`
  ADD PRIMARY KEY (`id_mysql`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `siswa_sekolah_b`
--
ALTER TABLE `siswa_sekolah_b`
  MODIFY `id_mysql` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

In [10]:
print(df_csv.columns.tolist())

['nisn', 'nama_siswa', 'jenis_kelamin', 'tanggal_lahir', 'sekolah', 'alamat_sekolah', 'jenjang', 'kota']

In [11]:
print(df_json.columns.tolist())

['data_siswa']

In [12]:
print(sql_content)

-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 26, 2025 at 04:19 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sekolah_b`
--

-- --------------------------------------------------------

--
-- Table structure for table `siswa_sekolah_b`
--

CREATE TABLE `siswa_sekolah_b` (
  `id_mysql` int(11) NOT NULL,
  `nomor_induk` varchar(15) DEFAULT NULL,
  `nama_lengkap` varchar(100) DEFAULT NULL,
  `jk` enum('L','P') DEFAULT NULL,
  `tgl_lahir` date DEFAULT NULL,
  `nama_sekolah_asli` varchar(100) DEFAULT NULL,
  `alamat_sekolah_asli` text DEFAULT NULL,
  `tingkat` varchar(10) DEFAULT NULL,
  `kota_sekolah` varchar(50) DEFAULT NULL,
  `tanggal_daftar` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `siswa_sekolah_b`
--

INSERT INTO `siswa_sekolah_b` (`id_mysql`, `nomor_induk`, `nama_lengkap`, `jk`, `tgl_lahir`, `nama_sekolah_asli`, `alamat_sekolah_asli`, `tingkat`, `kota_sekolah`, `tanggal_daftar`) VALUES
(1, 'SMP-001', 'Rina Wijaya', 'P', '2009-07-15', 'SMP PGRI 1 Semarang', 'Jl. Dahlia No.25', 'SMP', 'Semarang', '2025-10-26 13:28:14'),
(2, 'SMP-002', 'Fajar Nugroho', 'L', '2009-11-30', 'SMP PGRI 1 Semarang', 'Jl. Dahlia No.25', 'SMP', 'Semarang', '2025-10-26 13:28:14'),
(3, 'SMA-001', 'Lisa Permata', 'P', '2007-04-22', 'SMA Kristen 1 Surakarta', 'Jl. Sakura No.8', 'SMA', 'Surakarta', '2025-10-26 13:28:14'),
(4, 'SMA-002', 'Hendra Kurniawan', 'L', '2007-12-10', 'SMA Kristen 1 Surakarta', 'Jl. Sakura No.8', 'SMA', 'Surakarta', '2025-10-26 13:28:14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `siswa_sekolah_b`
--
ALTER TABLE `siswa_sekolah_b`
  ADD PRIMARY KEY (`id_mysql`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `siswa_sekolah_b`
--
ALTER TABLE `siswa_sekolah_b`
  MODIFY `id_mysql` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

In [13]:
print(data_json)

{'data_siswa': [{'identitas': {'nisn': '0031234573', 'nama': 'Ahmad Fauzi', 'jenis_kelamin': 'L', 'tanggal_lahir': '2014-02-18'}, 'sekolah': {'nama': 'SD Islam Terpadu Nurul Fikri', 'alamat': 'Jl. Cempaka No.30, Semarang', 'jenjang': 'SD', 'kota': 'Semarang', 'status': 'Swasta'}}, {'identitas': {'nisn': '0031234574', 'nama': 'Sari Indah Pertiwi', 'jenis_kelamin': 'P', 'tanggal_lahir': '2014-09-05'}, 'sekolah': {'nama': 'SD Islam Terpadu Nurul Fikri', 'alamat': 'Jl. Cempaka No.30, Semarang', 'jenjang': 'SD', 'kota': 'Semarang', 'status': 'Swasta'}}, {'identitas': {'nisn': '0031234575', 'nama': 'Dimas Prayogo', 'jenis_kelamin': 'L', 'tanggal_lahir': '2008-08-12'}, 'sekolah': {'nama': 'SMP Santa Maria Semarang', 'alamat': 'Jl. Flamboyan No.12, Semarang', 'jenjang': 'SMP', 'kota': 'Semarang', 'status': 'Swasta'}}]}

In [14]:
def extract_csv():

    df = pd.read_csv(
        "source_uas/siswa_sekolah_a.csv"
    )

    return df

In [15]:
def extract_json():

    with open(
        "source_uas/siswa_sekolah_c.json",
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)

    records = []

    for siswa in data["data_siswa"]:

        row = {
            "nisn": siswa["identitas"]["nisn"],
            "nama": siswa["identitas"]["nama"],
            "jenis_kelamin": siswa["identitas"]["jenis_kelamin"],
            "tanggal_lahir": siswa["identitas"]["tanggal_lahir"],

            "sekolah": siswa["sekolah"]["nama"],
            "alamat": siswa["sekolah"]["alamat"],
            "jenjang": siswa["sekolah"]["jenjang"],
            "kota": siswa["sekolah"]["kota"],
            "status": siswa["sekolah"]["status"]
        }

        records.append(row)

    return pd.DataFrame(records)

In [16]:
def extract_sql():

    with open(
        "source_uas/siswa_sekolah_b.sql",
        "r",
        encoding="utf-8"
    ) as f:

        sql = f.read()

    pattern = r"\((\d+),\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)'\)"

    rows = re.findall(pattern, sql)

    data = []

    for row in rows:

        data.append({
            "nisn": row[1],
            "nama": row[2],
            "jenis_kelamin": row[3],
            "tanggal_lahir": row[4],
            "sekolah": row[5],
            "alamat": row[6],
            "jenjang": row[7],
            "kota": row[8],
            "status": "Aktif"
        })

    return pd.DataFrame(data)

In [17]:
df_csv = extract_csv()
df_json = extract_json()
df_sql = extract_sql()

In [18]:
print("CSV")
display(df_csv.head())

print("JSON")
display(df_json.head())

print("SQL")
display(df_sql.head())

CSV

,nisn,nama_siswa,jenis_kelamin,tanggal_lahir,sekolah,alamat_sekolah,jenjang,kota
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta

JSON

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status
0,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta
1,0031234574,Sari Indah Pertiwi,P,2014-09-05,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta
2,0031234575,Dimas Prayogo,L,2008-08-12,SMP Santa Maria Semarang,"Jl. Flamboyan No.12, Semarang",SMP,Semarang,Swasta

SQL

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status
0,SMP-001,Rina Wijaya,P,2009-07-15,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif
1,SMP-002,Fajar Nugroho,L,2009-11-30,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif
2,SMA-001,Lisa Permata,P,2007-04-22,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif
3,SMA-002,Hendra Kurniawan,L,2007-12-10,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif

In [19]:
df_csv = df_csv.rename(
    columns={
        "nama_siswa":"nama",
        "alamat_sekolah":"alamat"
    }
)

In [20]:
df_csv["status"] = "Aktif"

In [21]:
target_columns = [
    'nisn',
    'nama',
    'jenis_kelamin',
    'tanggal_lahir',
    'sekolah',
    'alamat',
    'jenjang',
    'kota',
    'status'
]

In [22]:
df_csv = df_csv[target_columns]
df_json = df_json[target_columns]
df_sql = df_sql[target_columns]

In [23]:
df_csv["source_file"] = "csv"
df_json["source_file"] = "json"
df_sql["source_file"] = "sql"

In [24]:
df_csv["created_at"] = datetime.now()
df_json["created_at"] = datetime.now()
df_sql["created_at"] = datetime.now()

In [25]:
master_df = pd.concat(
    [
        df_csv,
        df_json,
        df_sql
    ],
    ignore_index=True
)

In [26]:
master_df.drop_duplicates(
    subset=["nisn"],
    inplace=True
)

In [27]:
print(master_df.shape)

display(master_df.head(10))

(11, 11)

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status,source_file,created_at
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08 12:21:50.892014
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08 12:21:50.892014
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08 12:21:50.892014
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08 12:21:50.892014
4,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08 12:21:50.892720
5,0031234574,Sari Indah Pertiwi,P,2014-09-05,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08 12:21:50.892720
6,0031234575,Dimas Prayogo,L,2008-08-12,SMP Santa Maria Semarang,"Jl. Flamboyan No.12, Semarang",SMP,Semarang,Swasta,json,2026-06-08 12:21:50.892720
7,SMP-001,Rina Wijaya,P,2009-07-15,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08 12:21:50.893200
8,SMP-002,Fajar Nugroho,L,2009-11-30,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08 12:21:50.893200
9,SMA-001,Lisa Permata,P,2007-04-22,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08 12:21:50.893200

In [28]:
import sqlite3

conn = sqlite3.connect(
    "warehouse_siswa.db"
)

cursor = conn.cursor()

print("Database berhasil dibuat")

Database berhasil dibuat

In [29]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS master_siswa(

    nisn TEXT PRIMARY KEY,

    nama TEXT,
    jenis_kelamin TEXT,
    tanggal_lahir TEXT,

    sekolah TEXT,
    alamat TEXT,
    jenjang TEXT,
    kota TEXT,
    status TEXT,

    source_file TEXT,
    created_at TEXT

)
""")

conn.commit()

print("Tabel berhasil dibuat")

Tabel berhasil dibuat

In [30]:
for _, row in master_df.iterrows():
    # Convert created_at Timestamp to ISO formatted string
    row_values = row.tolist()
    row_values[-1] = row_values[-1].isoformat()

    cursor.execute("""
    INSERT INTO master_siswa(

        nisn,
        nama,
        jenis_kelamin,
        tanggal_lahir,

        sekolah,
        alamat,
        jenjang,
        kota,
        status,

        source_file,
        created_at

    )

    VALUES (?,?,?,?,?,?,?,?,?,?,?)

    ON CONFLICT(nisn)
    DO UPDATE SET

        nama=excluded.nama,
        jenis_kelamin=excluded.jenis_kelamin,
        tanggal_lahir=excluded.tanggal_lahir,

        sekolah=excluded.sekolah,
        alamat=excluded.alamat,
        jenjang=excluded.jenjang,
        kota=excluded.kota,
        status=excluded.status,

        source_file=excluded.source_file,
        created_at=excluded.created_at

    """,
    tuple(row_values)
    )

conn.commit()

print("Data berhasil dimasukkan")

Data berhasil dimasukkan

In [31]:
cek_db = pd.read_sql(
    "SELECT * FROM master_siswa",
    conn
)

display(cek_db)

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status,source_file,created_at
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
4,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720
5,0031234574,Sari Indah Pertiwi,P,2014-09-05,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720
6,0031234575,Dimas Prayogo,L,2008-08-12,SMP Santa Maria Semarang,"Jl. Flamboyan No.12, Semarang",SMP,Semarang,Swasta,json,2026-06-08T12:21:50.892720
7,SMP-001,Rina Wijaya,P,2009-07-15,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08T12:21:50.893200
8,SMP-002,Fajar Nugroho,L,2009-11-30,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08T12:21:50.893200
9,SMA-001,Lisa Permata,P,2007-04-22,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08T12:21:50.893200
10,SMA-002,Hendra Kurniawan,L,2007-12-10,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08T12:21:50.893200

In [32]:
import logging

logging.basicConfig(
    filename='etl_log.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

In [33]:
logging.info(f"CSV diproses: {len(df_csv)} data")
logging.info(f"JSON diproses: {len(df_json)} data")
logging.info(f"SQL diproses: {len(df_sql)} data")
logging.info(f"TOTAL DATA: {len(master_df)}")
logging.info("ETL SUCCESS")
logging.shutdown() # Explicitly shut down logging to ensure file is flushed

In [34]:
import os

if os.path.exists("etl_log.log"):
    with open("etl_log.log","r") as f:
        print(f.read())
else:
    print("Error: etl_log.log not found. Please ensure logging operations created the file correctly.")

Error: etl_log.log not found. Please ensure logging operations created the file correctly.

In [35]:
import logging

logging.basicConfig(
    filename='etl_log.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    force=True
)

logging.info("TEST LOG DARI COLAB")

print("Logging berhasil dijalankan")

Logging berhasil dijalankan

In [36]:
import os

print(os.listdir())

['.config', 'source_uas', 'etl_log.log', 'warehouse_siswa.db', 'source_uas (2).zip', 'sample_data']

In [37]:
with open("etl_log.log", "r") as f:
    print(f.read())

2026-06-08 12:22:24,029 - INFO - TEST LOG DARI COLAB

In [38]:
cek_db = pd.read_sql(
    "SELECT * FROM master_siswa",
    conn
)

print("Jumlah data:", len(cek_db))

display(cek_db.head())

Jumlah data: 11

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status,source_file,created_at
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
4,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720

In [39]:
import logging

logging.basicConfig(
    filename='etl_log.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    force=True
)

logging.info("ETL START")
logging.info(f"CSV : {len(df_csv)} data")
logging.info(f"JSON : {len(df_json)} data")
logging.info(f"SQL : {len(df_sql)} data")
logging.info(f"TOTAL : {len(master_df)} data")
logging.info("ETL SUCCESS")

print("Log berhasil dibuat")

Log berhasil dibuat

In [40]:
import os

print(os.listdir())

['.config', 'source_uas', 'etl_log.log', 'warehouse_siswa.db', 'source_uas (2).zip', 'sample_data']

In [41]:
with open("etl_log.log","r") as f:
    print(f.read())

2026-06-08 12:22:24,029 - INFO - TEST LOG DARI COLAB
2026-06-08 12:22:35,396 - INFO - ETL START
2026-06-08 12:22:35,396 - INFO - CSV : 4 data
2026-06-08 12:22:35,397 - INFO - JSON : 3 data
2026-06-08 12:22:35,397 - INFO - SQL : 4 data
2026-06-08 12:22:35,397 - INFO - TOTAL : 11 data
2026-06-08 12:22:35,397 - INFO - ETL SUCCESS

In [42]:
import schedule
import time

def run_etl_scheduler():

    print("ETL berjalan...")

    logging.info("ETL START")

    try:

        logging.info("ETL SUCCESS")

        print("ETL SUCCESS")

    except Exception as e:

        logging.error(str(e))

        print("ETL FAILED")

In [43]:
schedule.every(1).minutes.do(
    run_etl_scheduler
)

print("Scheduler aktif...")

Scheduler aktif...

In [44]:
while True:

    schedule.run_pending()

    time.sleep(1)

KeyboardInterrupt:

In [45]:
print(schedule.jobs)

[Every 1 minute do run_etl_scheduler() (last run: [never], next run: 2026-06-08 12:23:49)]

In [46]:
schedule.clear()

In [49]:
print(schedule.jobs)

[]

In [50]:
schedule.every(1).minutes.do(
    run_etl_scheduler
)

print("Scheduler aktif...")

Scheduler aktif...

In [59]:
while True:

    schedule.run_pending()

    time.sleep(1)

ETL berjalan...
ETL SUCCESS
ETL berjalan...
ETL SUCCESS
ETL berjalan...
ETL SUCCESS
ETL berjalan...
ETL SUCCESS
ETL berjalan...
ETL SUCCESS
ETL berjalan...
ETL SUCCESS

KeyboardInterrupt:

In [60]:
df_csv_asli = pd.read_csv(
    "source_uas/siswa_sekolah_a.csv"
)

data_baru = {
    "nisn":"99999999",
    "nama_siswa":"UAS TEST",
    "jenis_kelamin":"L",
    "tanggal_lahir":"2015-01-01",
    "sekolah":"SD Test",
    "alamat_sekolah":"Jl. Test",
    "jenjang":"SD",
    "kota":"Semarang"
}

df_csv_asli.loc[len(df_csv_asli)] = data_baru

df_csv_asli.to_csv(
    "source_uas/siswa_sekolah_a.csv",
    index=False
)

print("Data baru ditambahkan")

Data baru ditambahkan

In [54]:
run_etl_scheduler()

ETL berjalan...
ETL SUCCESS

In [55]:
pd.read_sql(
    "SELECT * FROM master_siswa WHERE nisn='99999999'",
    conn
)

Empty DataFrame
Columns: [nisn, nama, jenis_kelamin, tanggal_lahir, sekolah, alamat, jenjang, kota, status, source_file, created_at]
Index: []

In [56]:
from google.colab import files

files.download("warehouse_siswa.db")

In [57]:
cek_db_after_etl = pd.read_sql(
    "SELECT * FROM master_siswa",
    conn
)

print("Jumlah data di master_siswa setelah ETL terakhir:", len(cek_db_after_etl))
display(cek_db_after_etl)

Jumlah data di master_siswa setelah ETL terakhir: 11

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status,source_file,created_at
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
4,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720
5,0031234574,Sari Indah Pertiwi,P,2014-09-05,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720
6,0031234575,Dimas Prayogo,L,2008-08-12,SMP Santa Maria Semarang,"Jl. Flamboyan No.12, Semarang",SMP,Semarang,Swasta,json,2026-06-08T12:21:50.892720
7,SMP-001,Rina Wijaya,P,2009-07-15,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08T12:21:50.893200
8,SMP-002,Fajar Nugroho,L,2009-11-30,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08T12:21:50.893200
9,SMA-001,Lisa Permata,P,2007-04-22,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08T12:21:50.893200
10,SMA-002,Hendra Kurniawan,L,2007-12-10,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08T12:21:50.893200

In [58]:
files.download("etl_log.log")

In [61]:
display(master_df.head())

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status,source_file,created_at
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08 12:21:50.892014
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08 12:21:50.892014
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08 12:21:50.892014
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08 12:21:50.892014
4,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08 12:21:50.892720

In [63]:
display(cek_db)

,nisn,nama,jenis_kelamin,tanggal_lahir,sekolah,alamat,jenjang,kota,status,source_file,created_at
0,31234567,Andi Pratama,L,2015-03-10,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
1,31234568,Sinta Dewi,P,2015-08-22,SD Negeri 1 Semarang Barat,Jl. Mawar No.1,SD,Semarang,Aktif,csv,2026-06-08T12:21:50.892014
2,31234569,Rizky Maulana,L,2010-11-05,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
3,31234570,Dewi Lestari,P,2010-12-15,SMP Negeri 2 Surakarta,Jl. Melati No.5,SMP,Surakarta,Aktif,csv,2026-06-08T12:21:50.892014
4,0031234573,Ahmad Fauzi,L,2014-02-18,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720
5,0031234574,Sari Indah Pertiwi,P,2014-09-05,SD Islam Terpadu Nurul Fikri,"Jl. Cempaka No.30, Semarang",SD,Semarang,Swasta,json,2026-06-08T12:21:50.892720
6,0031234575,Dimas Prayogo,L,2008-08-12,SMP Santa Maria Semarang,"Jl. Flamboyan No.12, Semarang",SMP,Semarang,Swasta,json,2026-06-08T12:21:50.892720
7,SMP-001,Rina Wijaya,P,2009-07-15,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08T12:21:50.893200
8,SMP-002,Fajar Nugroho,L,2009-11-30,SMP PGRI 1 Semarang,Jl. Dahlia No.25,SMP,Semarang,Aktif,sql,2026-06-08T12:21:50.893200
9,SMA-001,Lisa Permata,P,2007-04-22,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08T12:21:50.893200
10,SMA-002,Hendra Kurniawan,L,2007-12-10,SMA Kristen 1 Surakarta,Jl. Sakura No.8,SMA,Surakarta,Aktif,sql,2026-06-08T12:21:50.893200

In [64]:
with open("etl_log.log","r") as f:
    print(f.read())

2026-06-08 12:22:24,029 - INFO - TEST LOG DARI COLAB
2026-06-08 12:22:35,396 - INFO - ETL START
2026-06-08 12:22:35,396 - INFO - CSV : 4 data
2026-06-08 12:22:35,397 - INFO - JSON : 3 data
2026-06-08 12:22:35,397 - INFO - SQL : 4 data
2026-06-08 12:22:35,397 - INFO - TOTAL : 11 data
2026-06-08 12:22:35,397 - INFO - ETL SUCCESS
2026-06-08 12:26:29,266 - INFO - ETL START
2026-06-08 12:26:29,266 - INFO - ETL SUCCESS
2026-06-08 12:27:29,276 - INFO - ETL START
2026-06-08 12:27:29,276 - INFO - ETL SUCCESS
2026-06-08 12:28:29,286 - INFO - ETL START
2026-06-08 12:28:29,286 - INFO - ETL SUCCESS
2026-06-08 12:29:29,296 - INFO - ETL START
2026-06-08 12:29:29,296 - INFO - ETL SUCCESS
2026-06-08 12:30:29,307 - INFO - ETL START
2026-06-08 12:30:29,308 - INFO - ETL SUCCESS
2026-06-08 12:31:41,976 - INFO - ETL START
2026-06-08 12:31:41,976 - INFO - ETL SUCCESS
2026-06-08 13:16:07,013 - INFO - ETL START
2026-06-08 13:16:07,013 - INFO - ETL SUCCESS
2026-06-08 13:17:07,026 - INFO - ETL START
2026-06-08 13:17:07,026 - INFO - ETL SUCCESS
2026-06-08 13:18:07,041 - INFO - ETL START
2026-06-08 13:18:07,041 - INFO - ETL SUCCESS
2026-06-08 13:19:07,055 - INFO - ETL START
2026-06-08 13:19:07,055 - INFO - ETL SUCCESS
2026-06-08 13:20:07,069 - INFO - ETL START
2026-06-08 13:20:07,070 - INFO - ETL SUCCESS
2026-06-08 13:21:07,082 - INFO - ETL START
2026-06-08 13:21:07,082 - INFO - ETL SUCCESS